name: registry

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Use cached node_modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: nodeModules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          nodeModules-

    - name: Install deps
      run: yarn install --frozen-lockfile

    - name: Publish to GitHub Package Registry
      uses: actions/setup-node@v1
      with:
        registry-url: "https://npm.pkg.github.com"
        scope: "@soywod"

    - name: Publish to NPM Registry
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
