name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Use cached node_modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: nodeModules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          nodeModules-

    - name: Install deps
      run: yarn install --frozen-lockfile

    - name: Run tests
      run: yarn test --ci --coverage --maxWorkers=2
